services:

  cron:
    container_name: cron
    build:
      context: .
      dockerfile: ./config/cron.Containerfile
    volumes:
      - type: volume
        source: data
        target: /var/www/website-monitor/monitors
    working_dir: /var/www/website-monitor
    command: cron -f

  app:
    container_name: app
    depends_on:
      - cron
    build:
      context: .
      dockerfile: ./config/monitor.Containerfile
    volumes:
      - type: volume
        source: data
        target: /var/www/website-monitor/monitors
    ports:
      - "9000:9000"
    working_dir: /var/www/website-monitor
    command: php -S 0.0.0.0:9000 -f ./monitor.php

volumes:
  data:
