services:

  caddy:
    env_file: .env
    container_name: caddy-proxy
    image: caddy:latest
    ports:
      - "8000:8000"
      - "8787:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy-net

  web-monitor:
    env_file: .env
    container_name: web-monitor
    depends_on:
      - caddy
    build:
      dockerfile: Containerfile
    ports:
      - "9000:9000"
    networks:
      - proxy-net

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy-net:
