services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - ${CADDY_HTTP}
      - ${CADDY_HTTPS}
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

  cron:
    container_name: cron
    build:
      context: .
      dockerfile: ./conf/Containerfile
    volumes:
      - ./website-monitor:/var/www/website-monitor
    working_dir: /var/www/website-monitor

  app:
    image: php:8.2-fpm
    container_name: website-monitor
    depends_on:
      - caddy
      - cron
    volumes:
      - ./website-monitor:/var/www/website-monitor
    working_dir: /var/www/website-monitor
    command: php -S localhost:9000 -f ./monitor.php

volumes:
  caddy_data:
  caddy_config:
